---
- hosts: all

  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Perform a distribution upgrade
      apt:
        upgrade: full
        autoremove: yes
        autoclean: yes
