---
- hosts: all

  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Perform a distribution upgrade
      apt:
        upgrade: full
        autoremove: yes
        autoclean: yes
    - name: Execute ls -a command
      command: ls -a
      register: ls_output

    - name: Print ls -a output
      debug:
        msg: "{{ ls_output.stdout_lines }}"
